### ISSUE TITLE
Do not require 2 clicks to board vessels

### ISSUE THREAD

**Issue by o-fish-wildaid** [WildAid/o-fish-android#288] opened 2020-09-09 20:35 UTC
On the home page when you are not at sea and click the 'Board Vessel' button it asks if you want to change your status to 'At Sea'.

After a user is prompted to go at sea and selects 'Yes' they should be switched to 'at sea' and then the boarding should begin immediately. They shouldn't have to tap 'Board Vessel' again

**Comment by Sheeri** [comment] 2020-09-09 20:48
Closing, duplicate of #222

**Closed by Sheeri** 2020-09-09 20:48 UTC
Labels: bug
